"""
upstox/instruments.py
=====================
Loads NSE instruments from bundled CSV file (NSE_instruments.csv).

CSV columns: instrument_key, exchange_token, tradingsymbol, name,
             last_price, expiry, strike, tick_size, lot_size,
             instrument_type, option_type, exchange

Equity filter:
  - instrument_key starts with NSE_EQ
  - lot_size == 1  (bonds have lot_size=100)
  - tradingsymbol contains ONLY letters (no digits) — filters bonds like 749RJ35

To refresh instruments (do monthly):
  cd backend/upstox
  curl -L "https://assets.upstox.com/market-quote/instruments/exchange/NSE.csv.gz" -o NSE_instruments.csv.gz
  gunzip -f NSE_instruments.csv.gz
  git add NSE_instruments.csv && git commit -m "update NSE instruments"
"""

import csv
import io
import logging
import re
from pathlib import Path
from typing import Optional

from redis_client import get_redis

logger = logging.getLogger(__name__)

_CSV_PATH = Path(__file__).parent / "NSE_instruments.csv"
_REDIS_KEY = "upstox:instruments:nse_v3"
_REDIS_TTL = 86400

_symbol_map: dict  = {}
_symbol_meta: dict = {}
_loaded = False

# Real equity symbols: letters only + hyphen/ampersand. No digits.
# ETERNAL ✅  BAJAJ-AUTO ✅  M&M ✅  749RJ35 ❌  182D110626 ❌
_EQUITY_RE = re.compile(r'^[A-Z][A-Z&-]{1,19}$')


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def get_instrument_key(symbol: str) -> Optional[str]:
    await _ensure_loaded()
    key = _symbol_map.get(symbol.upper().strip())
    if not key:
        logger.warning("Symbol '%s' not found in instruments master", symbol)
    return key


async def get_instrument_keys_bulk(symbols: list) -> dict:
    await _ensure_loaded()
    return {sym: _symbol_map.get(sym.upper().strip()) for sym in symbols}


async def search_instruments(query: str, limit: int = 20) -> list:
    await _ensure_loaded()
    q = query.upper().strip()
    results = []
    for symbol, meta in _symbol_meta.items():
        if q in symbol or q in meta.get("name", "").upper():
            results.append({
                "symbol": symbol,
                "instrument_key": meta["instrument_key"],
                "name": meta["name"],
            })
            if len(results) >= limit:
                break
    return results


async def reload_instruments() -> int:
    global _loaded
    _symbol_map.clear()
    _symbol_meta.clear()
    _loaded = False
    try:
        redis = await get_redis()
        await redis.delete(_REDIS_KEY)
    except Exception:
        pass
    await _load_instruments()
    return len(_symbol_map)


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------

async def _ensure_loaded() -> None:
    if _loaded and _symbol_map:
        return
    await _load_instruments()


async def _load_instruments() -> None:
    global _loaded

    # 1. Try Redis cache
    try:
        redis = await get_redis()
        cached = await redis.get(_REDIS_KEY)
        if cached:
            _parse_csv(cached)
            _loaded = True
            logger.info("Instruments loaded from Redis: %d symbols", len(_symbol_map))
            return
    except Exception as e:
        logger.warning("Redis read failed: %s", e)

    # 2. Load from bundled CSV
    if not _CSV_PATH.exists():
        logger.error("NSE_instruments.csv not found at %s", _CSV_PATH)
        _loaded = True
        return

    logger.info("Loading instruments from %s", _CSV_PATH)
    text = _CSV_PATH.read_text(encoding="utf-8", errors="replace")
    _parse_csv(text)

    # 3. Cache in Redis
    try:
        redis = await get_redis()
        await redis.set(_REDIS_KEY, text, ex=_REDIS_TTL)
    except Exception:
        pass

    _loaded = True
    logger.info("Instruments ready: %d NSE equity symbols", len(_symbol_map))


def _parse_csv(text: str) -> None:
    _symbol_map.clear()
    _symbol_meta.clear()
    count = 0

    reader = csv.DictReader(io.StringIO(text))

    for row in reader:
        row = {k.strip(): v.strip() for k, v in row.items() if k}

        instrument_key = row.get("instrument_key", "")
        symbol         = row.get("tradingsymbol", "").upper().strip()
        name           = row.get("name", "")
        lot_size_str   = row.get("lot_size", "1")

        # Must be NSE equity
        if not instrument_key.startswith("NSE_EQ"):
            continue

        # lot_size must be 1 — bonds/SDL have lot_size=100
        try:
            if int(lot_size_str) != 1:
                continue
        except (ValueError, TypeError):
            pass

        # Symbol must be letters only — no digits
        if not symbol or not _EQUITY_RE.match(symbol):
            continue

        meta = {"instrument_key": instrument_key, "name": name}
        _symbol_map[symbol] = instrument_key
        _symbol_meta[symbol] = meta

        # Register aliases: BAJAJ-AUTO <-> BAJAJ_AUTO, M&M -> MM
        for alias in _aliases(symbol):
            if alias not in _symbol_map:
                _symbol_map[alias] = instrument_key
                _symbol_meta[alias] = meta

        count += 1

    logger.info("Parsed %d equity instruments (bonds filtered)", count)


def _aliases(symbol: str) -> list:
    out = []
    if "-" in symbol:
        out.append(symbol.replace("-", "_"))
    if "_" in symbol:
        out.append(symbol.replace("_", "-"))
    if "&" in symbol:
        out.append(symbol.replace("&", ""))
    return out


# ---------------------------------------------------------------------------
# Nifty universe
# ---------------------------------------------------------------------------

ALL_NSE_SYMBOLS: set = {
    "AAATECH", "AADHARHFC", "AAKASH", "AAREYDRUGS", "AARNAV", "AARON", "AARTECH", "AARTIDRUGS",
    "AARTIIND", "AARTIPHARM", "AARTISURF", "AARVI", "AAVAS", "ABANSENT", "ABB", "ABBOTINDIA",
    "ABCAPITAL", "ABCOTS", "ABDL", "ABFRL", "ABGSEC", "ABINFRA", "ABLBL", "ABMINTLLTD",
    "ABMKNO", "ABREL", "ABSLAMC", "ABSLBANETF", "ABSLLIQUID", "ABSLMSCIN", "ABSLPSE", "ACC",
    "ACCELYA", "ACCURACY", "ACE", "ACEINTEG", "ACI", "ACL", "ACMESOLAR", "ACSTECH",
    "ACUTAAS", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ADFFOODS", "ADL",
    "ADOR", "ADROITINFO", "ADSL", "ADVAIT", "ADVANCE", "ADVANIHOTR", "ADVENTHTL", "ADVENZYMES",
    "AEGISLOG", "AEGISVOPAK", "AEPL", "AEQUS", "AEROENTER", "AEROFLEX", "AERONEU", "AETHER",
    "AFCONS", "AFFLE", "AFFORDABLE", "AFIL", "AFSL", "AGARIND", "AGARWALEYE", "AGI",
    "AGIIL", "AGRITECH", "AGROPHOS", "AHCL", "AHLADA", "AHLEAST", "AHLUCONT", "AHLWEST",
    "AIAENG", "AIIL", "AIRAN", "AIROLAM", "AJANTPHARM", "AJAXENGG", "AJMERA", "AJOONI",
    "AKASH", "AKCAPIT", "AKG", "AKI", "AKSHAR", "AKSHARCHEM", "AKSHOPTFBR", "AKUMS",
    "ALANKIT", "ALBERTDAVD", "ALEMBICLTD", "ALGOQUANT", "ALICON", "ALIVUS", "ALKALI", "ALKEM",
    "ALKYLAMINE", "ALLCARGO", "ALLDIGI", "ALLTIME", "ALMONDZ", "ALOKINDS", "ALPA", "ALPHA",
    "ALPHAETF", "ALPHAGEO", "AMAGI", "AMANTA", "AMBALALSA", "AMBER", "AMBICAAGAR", "AMBIKCO",
    "AMBUJACEM", "AMDIND", "AMIRCHAND", "AMJLAND", "AMNPLST", "AMRUTANJAN", "ANANDRATHI", "ANANTAM",
    "ANANTRAJ", "ANDHRAPAP", "ANDHRSUGAR", "ANGELONE", "ANIKINDS", "ANKITMETAL", "ANMOL", "ANSALAPI",
    "ANTELOPUS", "ANTGRAPHIC", "ANTHEM", "ANUHPHR", "ANUP", "ANURAS", "AONEGOLD", "AONELIQUID",
    "AONENIFTY", "AONESILVER", "AONETOTAL", "APARINDS", "APCL", "APCOTEXIND", "APEX", "APLAPOLLO",
    "APLLTD", "APOLLO", "APOLLOHOSP", "APOLLOPIPE", "APOLLOTYRE", "APOLSINHOT", "APTECHT", "APTUS",
    "AQYLON", "ARCHIDPLY", "ARCHIES", "ARE&M", "ARENTERP", "ARFIN", "ARIES", "ARIHANT",
    "ARIHANTCAP", "ARIHANTSUP", "ARIS", "ARKADE", "ARMANFIN", "AROGRANITE", "ARROWGREEN", "ARSHIYA",
    "ARSSBL", "ARTEMISMED", "ARTNIRMAN", "ARVEE", "ARVIND", "ARVINDFASN", "ARVSMART", "ASAHIINDIA",
    "ASAHISONG", "ASAL", "ASALCBR", "ASHAPURMIN", "ASHIANA", "ASHIKA", "ASHIMASYN", "ASHOKA",
    "ASHOKAMET", "ASHOKLEY", "ASIANENE", "ASIANHOTNR", "ASIANPAINT", "ASIANTILES", "ASKAUTOLTD", "ASMS",
    "ASPINWALL", "ASTAR", "ASTEC", "ASTERDM", "ASTRAL", "ASTRAMICRO", "ASTRAZEN", "ASTRON",
    "ATALREAL", "ATAM", "ATGL", "ATHERENERG", "ATL", "ATLANTAA", "ATLANTAELE", "ATLASCYCLE",
    "ATLPP", "ATUL", "ATULAUTO", "AUBANK", "AURIGROW", "AURIONPRO", "AUROPHARMA", "AURUM",
    "AUSOMENT", "AUTOAXLES", "AUTOBEES", "AUTOIETF", "AUTOIND", "AVADHSUGAR", "AVAILFC", "AVALON",
    "AVANTEL", "AVANTIFEED", "AVG", "AVL", "AVONMORE", "AVROIND", "AVTNPL", "AWFIS",
    "AWHCL", "AWL", "AXISBANK", "AXISBNKETF", "AXISCADES", "AXISCETF", "AXISGOLD", "AXISHCETF",
    "AXISILVER", "AXISNIFTY", "AXISTECETF", "AXISVALUE", "AXITA", "AXSENSEX", "AYE", "AYMSYNTEX",
    "AZAD", "BAFNAPH", "BAGFILMS", "BAGMANE", "BAIDFIN", "BAJAJ-AUTO", "BAJAJCON", "BAJAJELEC",
    "BAJAJFINSV", "BAJAJHCARE", "BAJAJHFL", "BAJAJHIND", "BAJAJHLDNG", "BAJAJINDEF", "BAJAJST", "BAJEL",
    "BAJFINANCE", "BALAJEE", "BALAJITELE", "BALAMINES", "BALAXI", "BALKRISHNA", "BALKRISIND", "BALMLAWRIE",
    "BALPHARMA", "BALRAMCHIN", "BALUFORGE", "BANARBEADS", "BANARISUG", "BANCOINDIA", "BANDHANBNK", "BANG",
    "BANKA", "BANKADD", "BANKBARODA", "BANKBEES", "BANKBETA", "BANKBETF", "BANKETF", "BANKIETF",
    "BANKINDIA", "BANKPSU", "BANSALWIRE", "BANSWRAS", "BASF", "BASML", "BATAINDIA", "BATLIBOI",
    "BAYERCROP", "BBL", "BBNPNBETF", "BBNPPGOLD", "BBOX", "BBTC", "BBTCL", "BCG",
    "BCLIND", "BCONCEPTS", "BCPL", "BDL", "BEARDSELL", "BECTORFOOD", "BEDMUTHA", "BEEKAY",
    "BEL", "BELLACASA", "BELRISE", "BEML", "BENGALASM", "BEPL", "BERGEPAINT", "BESTAGRO",
    "BETA", "BFINVEST", "BFSI", "BFUTILITIE", "BGRENERGY", "BHAGCHEM", "BHAGERIA", "BHAGYANGR",
    "BHANDARI", "BHARATCOAL", "BHARATFORG", "BHARATGEAR", "BHARATRAS", "BHARATSE", "BHARATWIRE", "BHARTIARTL",
    "BHARTIHEXA", "BHEL", "BI", "BIGBLOC", "BIKAJI", "BIL", "BIMETAL", "BIOCON",
    "BIOFILCHEM", "BIRET", "BIRLACABLE", "BIRLACORPN", "BIRLAMONEY", "BIRLANU", "BIRLAPREC", "BLACKBUCK",
    "BLACKROSE", "BLAL", "BLBLIMITED", "BLIL", "BLISSGVS", "BLKASHYAP", "BLS", "BLSE",
    "BLUECHIP", "BLUECOAST", "BLUEDART", "BLUEJET", "BLUESTARCO", "BLUESTONE", "BLUSPRING", "BMWVENTLTD",
    "BNAGROCHEM", "BNALTD", "BODALCHEM", "BOHRAIND", "BOMDYEING", "BONLON", "BORANA", "BOROLTD",
    "BORORENEW", "BOROSCI", "BOSCH-HCIL", "BOSCHLTD", "BPCL", "BPL", "BRIGADE", "BRIGHOTEL",
    "BRITANNIA", "BRNL", "BROOKS", "BSE", "BSHSL", "BSL", "BSLGOLDETF", "BSLNIFTY",
    "BSLSENETFG", "BSOFT", "BTML", "BTTL", "BUILDPRO", "BUTTERFLY", "BVCL", "BYKE",
    "CALSOFT", "CAMLINFINE", "CAMPUS", "CAMS", "CANBK", "CANFINHOME", "CANHLIFE", "CANTABIL",
    "CAPACITE", "CAPILLARY", "CAPINVIT", "CAPITALSFB", "CAPLIPOINT", "CAPTRUST", "CARBORUNIV", "CARERATING",
    "CARRARO", "CARTRADE", "CARYSIL", "CASHIETF", "CASTROLIND", "CCAVENUE", "CCCL", "CCHHL",
    "CCL", "CDSL", "CEATLTD", "CEIGALL", "CEINSYS", "CELEBRITY", "CELLO", "CEMPRO",
    "CENTENKA", "CENTEXT", "CENTRALBK", "CENTRUM", "CENTUM", "CENTURYPLY", "CERA", "CEREBRAINT",
    "CESC", "CEWATER", "CGCL", "CGPOWER", "CHALET", "CHAMBLFERT", "CHEMBOND", "CHEMBONDCH",
    "CHEMCON", "CHEMFAB", "CHEMICAL", "CHEMPLASTS", "CHENNPETRO", "CHEVIOT", "CHOICEGOLD", "CHOICEIN",
    "CHOLAFIN", "CHOLAHLDNG", "CIEINDIA", "CIFL", "CINELINE", "CINEVISTA", "CIPLA", "CITIUSINVT",
    "CLEAN", "CLEANMAX", "CLEDUCATE", "CLSEL", "CMPDI", "CMSINFO", "CNL", "COALINDIA",
    "COASTCORP", "COCHINSHIP", "COCKERILL", "COFFEEDAY", "COFORGE", "COHANCE", "COLPAL", "COMFINTE",
    "COMMOIETF", "COMPINFO", "COMPUSOFT", "COMSYN", "CONCOR", "CONCORDBIO", "CONFIPET", "CONS",
    "CONSOFINVT", "CONSUMBEES", "CONSUMER", "CONSUMIETF", "CONTROLPR", "CORALFINAC", "CORDSCABLE", "COROMANDEL",
    "CORONA", "COSMOFIRST", "COUNCODOS", "CPCAP", "CPEDU", "CPPLUS", "CPSEETF", "CRAFTSMAN",
    "CRAMC", "CREATIVEYE", "CREDITACC", "CREST", "CRISIL", "CRIZAC", "CROMPTON", "CROWN",
    "CSBBANK", "CSLFINANCE", "CTE", "CUB", "CUBEXTUB", "CUMMINSIND", "CUPID", "CURAA",
    "CYBERMEDIA", "CYBERTECH", "CYIENT", "CYIENTDLM", "DABUR", "DAICHI", "DALBHARAT", "DALMIASUG",
    "DAMCAPITAL", "DAMODARIND", "DANGEE", "DATAMATICS", "DATAPATTNS", "DAVANGERE", "DBCORP", "DBEIL",
    "DBL", "DBOL", "DBREALTY", "DBSTOCKBRO", "DCAL", "DCBBANK", "DCI", "DCM",
    "DCMFINSERV", "DCMNVL", "DCMSHRIRAM", "DCMSIL", "DCMSRIND", "DCW", "DCXINDIA", "DDEVPLSTIK",
    "DECCANCE", "DECNGOLD", "DEEDEV", "DEEPAKFERT", "DEEPAKNTR", "DEEPINDS", "DEFENCE", "DELHIVERY",
    "DELPHIFX", "DELTACORP", "DELTAMAGNT", "DEN", "DENORA", "DENTA", "DEVIT", "DEVX",
    "DEVYANI", "DGCONTENT", "DHAMPURSUG", "DHANBANK", "DHANUKA", "DHARMAJ", "DHRUV", "DHUNINV",
    "DIACABS", "DIAMINESQ", "DIAMONDYD", "DICIND", "DIFFNKG", "DIGIDRIVE", "DIGISPICE", "DIGITIDE",
    "DIGJAMLMTD", "DISAQ", "DISHTV", "DIVGIITTS", "DIVIDEND", "DIVISLAB", "DIVOPPBEES", "DIXON",
    "DJML", "DLF", "DLINKINDIA", "DMART", "DMCC", "DNAMEDIA", "DODLA", "DOLATALGO",
    "DOLLAR", "DOLPHIN", "DOMS", "DONEAR", "DPABHUSHAN", "DPSCLTD", "DPWIRES", "DRAGARWQ",
    "DRCSYSTEMS", "DREAMFOLKS", "DREDGECORP", "DRREDDY", "DSFCL", "DSSL", "DTIL", "DUCON",
    "DVL", "DWARKESH", "DYCL", "DYNAMATECH", "DYNPRO", "EASEMYTRIP", "EASTSILK", "EBANKNIFTY",
    "EBGNG", "ECAPINSURE", "ECLERX", "ECOSMOBLTY", "EDELWEISS", "EFCIL", "EGOLD", "EICHERMOT",
    "EIDPARRY", "EIEL", "EIFFL", "EIHAHOTELS", "EIHOTEL", "EIMCOELECO", "EKC", "ELANTAS",
    "ELCIDIN", "ELDEHSG", "ELECON", "ELECTCAST", "ELECTHERM", "ELGIEQUIP", "ELGIRUBCO", "ELIN",
    "ELIQUID", "ELITECON", "ELLEN", "ELPROINTL", "EMAMILTD", "EMAMIPAP", "EMAMIREAL", "EMBASSY",
    "EMBDL", "EMCURE", "EMIL", "EMKAY", "EMMBI", "EMMVEE", "EMPOWER", "EMSLIMITED",
    "EMUDHRA", "EMULTIMQ", "ENDURANCE", "ENERGY", "ENERGYDEV", "ENGINERSIN", "ENIFTY", "ENIL",
    "ENRIN", "ENTERO", "EPACK", "EPACKPEB", "EPIGRAL", "EPL", "EQUIPPP", "EQUITASBNK",
    "ERIS", "ESABINDIA", "ESAFSFB", "ESCORTS", "ESENSEX", "ESG", "ESILVER", "ESSARSHPNG",
    "ESSENTIA", "ESTER", "ETERNAL", "ETHOSLTD", "EUREKAFORB", "EUROBOND", "EUROPRATIK", "EUROTEXIND",
    "EVEREADY", "EVERESTIND", "EVIETF", "EVINDIA", "EXCELINDUS", "EXCELSOFT", "EXICOM", "EXIDEIND",
    "EXPLEOSOL", "EXXARO", "FABTECH", "FACT", "FAIRCHEMOR", "FCL", "FCSSOFT", "FDC",
    "FEDDERSHOL", "FEDERALBNK", "FEDFINA", "FEL", "FELDVR", "FERMENTA", "FIBERWEB", "FIEMIND",
    "FILATEX", "FILATFASH", "FINCABLES", "FINEORG", "FINIETF", "FINKURVE", "FINOPB", "FINPIPE",
    "FIRSTCRY", "FISCHER", "FIVESTAR", "FLAIR", "FLEXIADD", "FLEXITUFF", "FLFL", "FLUOROCHEM",
    "FMCGIETF", "FMGOETZE", "FMNL", "FOCUS", "FOODSIN", "FORCEMOT", "FORTIS", "FOSECOIND",
    "FRACTAL", "FRONTSP", "FSL", "FUSION", "GABRIEL", "GAEL", "GAIL", "GALAPREC",
    "GALAXYSURF", "GALLANTT", "GANDHAR", "GANDHITUBE", "GANECOS", "GANESHBE", "GANESHCP", "GANESHHOU",
    "GANGAFORGE", "GANGESSECU", "GARFIBRES", "GARUDA", "GATECH", "GATECHDVR", "GATEWAY", "GAUDIUMIVF",
    "GAYAHWS", "GAYAPROJ", "GCSL", "GEECEE", "GEEKAYWIRE", "GEMAROMA", "GENCON", "GENESYS",
    "GENUSPAPER", "GENUSPOWER", "GEOJITFSL", "GESHIP", "GFLLIMITED", "GHCL", "GHCLTEXTIL", "GICHSGFIN",
    "GICL", "GICRE", "GILLANDERS", "GILLETTE", "GINNIFILA", "GIPCL", "GKENERGY", "GKSL",
    "GKWLIMITED", "GLAND", "GLAXO", "GLENMARK", "GLFL", "GLOBAL", "GLOBALE", "GLOBALVECT",
    "GLOBE", "GLOBECIVIL", "GLOBUSSPR", "GLOSTERLTD", "GLOTTIS", "GMBREW", "GMDCLTD", "GMMPFAUDLR",
    "GMRAIRPORT", "GMRP&UI", "GNA", "GNFC", "GNRL", "GOACARBON", "GOCLCORP", "GOCOLORS",
    "GODAVARIB", "GODFRYPHLP", "GODIGIT", "GODREJAGRO", "GODREJCP", "GODREJIND", "GODREJPROP", "GOKEX",
    "GOKUL", "GOKULAGRO", "GOLDADD", "GOLDBEES", "GOLDBETA", "GOLDBND", "GOLDCASE", "GOLDENTOBC",
    "GOLDETF", "GOLDIAM", "GOLDIETF", "GOLDTECH", "GOODLUCK", "GOODYEAR", "GOPAL", "GOYALALUM",
    "GPIL", "GPPL", "GPTHEALTH", "GPTINFRA", "GRADIENTE", "GRANDOAK", "GRANULES", "GRAPHITE",
    "GRASIM", "GRAUWEIL", "GRAVISSHO", "GRAVITA", "GREAVESCOT", "GREENLAM", "GREENPANEL", "GREENPLY",
    "GREENPOWER", "GRINDWELL", "GRINFRA", "GRMOVER", "GROBTEA", "GROWW", "GROWWCAPM", "GROWWCHEM",
    "GROWWDEFNC", "GROWWEV", "GROWWGOLD", "GROWWHOSPI", "GROWWLIQID", "GROWWLOVOL", "GROWWMETAL", "GROWWNET",
    "GROWWNIFTY", "GROWWPOWER", "GROWWPSE", "GROWWPSUBK", "GROWWRAIL", "GROWWRLTY", "GROWWSLVR", "GRPLTD",
    "GRSE", "GRWRHITECH", "GSFC", "GSLSU", "GSPCROP", "GSS", "GTECJAINX", "GTL",
    "GTLINFRA", "GTPL", "GUFICBIO", "GUJALKALI", "GUJAPOLLO", "GUJGASLTD", "GUJRAFFIA", "GUJTHEM",
    "GULFOILLUB", "GULFPETRO", "GULPOLY", "GVKPIL", "GVPIL", "GVPTECH", "GVPTECHPP", "GVT&D",
    "HAL", "HALDER", "HALDYNGL", "HALEOSLABS", "HAPPSTMNDS", "HAPPYFORGE", "HARDWYN", "HARIOMPIPE",
    "HARRMALAYA", "HARSHA", "HATHWAY", "HATSUN", "HAVELLS", "HAVISHA", "HAWKINCOOK", "HBESD",
    "HBLENGINE", "HBSL", "HCC", "HCG", "HCL-INSYS", "HCLTECH", "HDBFS", "HDFCAMC",
    "HDFCBANK", "HDFCGOLD", "HDFCGROWTH", "HDFCLIFE", "HDFCLIQUID", "HDFCLOWVOL", "HDFCMOMENT", "HDFCNIFBAN",
    "HDFCNIFIT", "HDFCNIFTY", "HDFCPSUBK", "HDFCPVTBAN", "HDFCQUAL", "HDFCSENSEX", "HDFCSILVER", "HDFCVALUE",
    "HDIL", "HEADSUP", "HEALTHADD", "HEALTHCARE", "HEALTHIETF", "HEALTHX", "HEALTHY", "HECPROJECT",
    "HEG", "HEIDELBERG", "HEMIPROP", "HERANBA", "HERITGFOOD", "HEROMOTOCO", "HESTERBIO", "HEXATRADEX",
    "HEXT", "HFCL", "HGINFRA", "HGM", "HGS", "HIKAL", "HILINFRA", "HILTON",
    "HIMATSEIDE", "HINDALCO", "HINDCOMPOS", "HINDCON", "HINDCOPPER", "HINDOILEXP", "HINDPETRO", "HINDUNILVR",
    "HINDWAREAP", "HINDZINC", "HIRECT", "HISARMETAL", "HITECH", "HITECHCORP", "HITECHGEAR", "HLEGLAS",
    "HLVLTD", "HMAAGRO", "HMT", "HMVL", "HNDFDS", "HNGSNGBEES", "HOMEFIRST", "HONASA",
    "HONAUT", "HONDAPOWER", "HPAL", "HPIL", "HPL", "HSBCGOLD", "HSCL", "HTMEDIA",
    "HUBTOWN", "HUDCO", "HUHTAMAKI", "HYBRIDFIN", "HYUNDAI", "IBULLSLTD", "ICDSLTD", "ICEMAKE",
    "ICICIAMC", "ICICIBANK", "ICICIGI", "ICICIPRULI", "ICIL", "ICRA", "IDBI", "IDEA",
    "IDEAFORGE", "IDFCFIRSTB", "IDFNIFTYET", "IEX", "IFBAGRO", "IFBIND", "IFCI", "IFGLEXPOR",
    "IGARASHI", "IGCL", "IGIL", "IGL", "IGPL", "IIFL", "IIFLCAPS", "IITL",
    "IKIO", "IKS", "IL&FSENGG", "IL&FSTRANS", "IMAGICAA", "IMFA", "IMPAL", "IMPEXFERRO",
    "INA", "INCREDIBLE", "INDBANK", "INDGN", "INDHOTEL", "INDIACEM", "INDIAGLYCO", "INDIAMART",
    "INDIANB", "INDIANCARD", "INDIANHUME", "INDIASHLTR", "INDIGO", "INDIGOPNTS", "INDIGRID", "INDIQUBE",
    "INDNIPPON", "INDOAMIN", "INDOBORAX", "INDOCO", "INDOFARM", "INDORAMA", "INDOSTAR", "INDOTECH",
    "INDOTHAI", "INDOUS", "INDOWIND", "INDPRUD", "INDRAMEDCO", "INDSWFTLAB", "INDTERRAIN", "INDUSINDBK",
    "INDUSINVIT", "INDUSTOWER", "INFOBEAN", "INFOMEDIA", "INFRA", "INFRABEES", "INFRAIETF", "INFY",
    "INGERRAND", "INNOVACAP", "INNOVANA", "INNOVISION", "INOXGREEN", "INOXINDIA", "INOXWIND", "INSECTICID",
    "INSPIRISYS", "INTELLECT", "INTENTECH", "INTERARCH", "INTERNET", "INTLCONV", "INVENTURE", "INVPRECQ",
    "IOB", "IOC", "IOLCP", "IONEXCHANG", "IPCALAB", "IPL", "IRB", "IRBINVIT",
    "IRCON", "IRCTC", "IREDA", "IRFC", "IRIS", "IRISDOREME", "IRMENERGY", "ISFT",
    "ISGEC", "ISHANCH", "IT", "ITADD", "ITBEES", "ITBETA", "ITC", "ITCHOTELS",
    "ITDC", "ITETF", "ITI", "ITIETF", "IVALUE", "IVC", "IVP", "IVZINGOLD",
    "IVZINNIFTY", "IWP", "IXIGO", "IZMO", "J&KBANK", "JAGRAN", "JAGSNPHARM", "JAIBALAJI",
    "JAICORPLTD", "JAINREC", "JAIPURKURT", "JAMNAAUTO", "JARO", "JASH", "JAYAGROGN", "JAYBARMARU",
    "JAYKAY", "JAYNECOIND", "JAYSREETEA", "JBCHEPHARM", "JBMA", "JETFREIGHT", "JGCHEM", "JHS",
    "JINDALPHOT", "JINDALPOLY", "JINDALSAW", "JINDALSTEL", "JINDRILL", "JINDWORLD", "JIOFIN", "JISLDVREQS",
    "JISLJALEQS", "JITFINFRA", "JKCEMENT", "JKIL", "JKIPL", "JKLAKSHMI", "JKPAPER", "JKTYRE",
    "JLHL", "JMA", "JMFINANCIL", "JNKINDIA", "JOCIL", "JPOLYINVST", "JPPOWER", "JSFB",
    "JSL", "JSLL", "JSWCEMENT", "JSWDULUX", "JSWENERGY", "JSWHL", "JSWINFRA", "JSWSTEEL",
    "JTEKTINDIA", "JTLIND", "JUBLCPL", "JUBLFOOD", "JUBLINGREA", "JUBLPHARMA", "JUNIORBEES", "JUNIPER",
    "JUSTDIAL", "JWL", "JYOTHYLAB", "JYOTICNC", "JYOTISTRUC", "KABRAEXTRU", "KAJARIACER", "KAKATCEM",
    "KALAMANDIR", "KALPATARU", "KALYANI", "KALYANIFRG", "KALYANKJIL", "KAMAHOLD", "KAMATHOTEL", "KAMDHENU",
    "KAMOPAINTS", "KANANIIND", "KANCHI", "KANORICHEM", "KANPRPLA", "KANSAINER", "KAPSTON", "KARMAENG",
    "KARURVYSYA", "KAUSHALYA", "KAVDEFENCE", "KAYA", "KAYNES", "KCP", "KCPSUGIND", "KDDL",
    "KEC", "KECL", "KEEPLEARN", "KEI", "KELLTONTEC", "KENNAMET", "KERNEX", "KESORAMIND",
    "KEYFINSERV", "KFINTECH", "KHADIM", "KHAICHEM", "KHAITANLTD", "KHANDSE", "KICL", "KILITCH",
    "KIMS", "KINGFA", "KIOCL", "KIRANVYPAR", "KIRIINDUS", "KIRLFER", "KIRLOSBROS", "KIRLOSENG",
    "KIRLOSIND", "KIRLPNU", "KISSHT", "KITEX", "KKCL", "KLBRENG-B", "KMEW", "KMSUGAR",
    "KNAGRI", "KNRCON", "KOHINOOR", "KOKUYOCMLN", "KOLTEPATIL", "KOPRAN", "KOTAKBANK", "KOTARISUG",
    "KOTHARIPET", "KOTHARIPRO", "KOTIC", "KOTYARK", "KOVAI", "KPEL", "KPIGREEN", "KPIL",
    "KPITTECH", "KPL", "KPRMILL", "KRBL", "KREBSBIO", "KRIDHANINF", "KRISHANA", "KRISHIVAL",
    "KRISHNADEF", "KRISHPP", "KRITI", "KRITIKA", "KRITINUT", "KRN", "KRONOX", "KROSS",
    "KRSNAA", "KRT", "KRYSTAL", "KSB", "KSCL", "KSHINTL", "KSHITIJPOL", "KSL",
    "KSOLVES", "KSR", "KTKBANK", "KUANTUM", "KWIL", "LAGNAM", "LAHOTIOV", "LAKPRE",
    "LAL", "LALPATHLAB", "LAMBODHARA", "LANCORHOL", "LANDMARK", "LANDSMILL", "LAOPALA", "LASA",
    "LATENTVIEW", "LATTEYS", "LAURUSLABS", "LAXMICOT", "LAXMIDENTL", "LAXMIINDIA", "LCCINFOTEC", "LEMERITE",
    "LEMONTREE", "LENSKART", "LEXUS", "LFIC", "LGBBROSLTD", "LGEINDIA", "LGHL", "LIBAS",
    "LIBERTSHOE", "LICHSGFIN", "LICI", "LICMFGOLD", "LICNETFGSC", "LICNETFSEN", "LICNFNHGP", "LIKHITHA",
    "LINC", "LINCOLN", "LINDEINDIA", "LIQGRWBEES", "LIQUID", "LIQUIDADD", "LIQUIDBEES", "LIQUIDBETF",
    "LIQUIDCASE", "LIQUIDETF", "LIQUIDIETF", "LIQUIDPLUS", "LIQUIDSBI", "LIQUIDSHRI", "LLOYDSENGG", "LLOYDSENT",
    "LLOYDSME", "LMW", "LODHA", "LOKESHMACH", "LORDSCHLO", "LOTUSDEV", "LOTUSEYE", "LOVABLE",
    "LOWVOL", "LOWVOLIETF", "LOYALTEX", "LPDC", "LT", "LTF", "LTFOODS", "LTGILTBEES",
    "LTGILTCASE", "LTM", "LTTS", "LUMAXIND", "LUMAXTECH", "LUPIN", "LUXIND", "LXCHEM",
    "LYKALABS", "LYPSAGEMS", "M&M", "M&MFIN", "MAANALU", "MACPOWER", "MADHAV", "MADHAVIPL",
    "MADHUCON", "MADRASFERT", "MAFANG", "MAFATIND", "MAGADSUGAR", "MAGNUM", "MAHABANK", "MAHAPEXLTD",
    "MAHASTEEL", "MAHEPC", "MAHESHWARI", "MAHKTECH", "MAHLIFE", "MAHLOG", "MAHSCOOTER", "MAHSEAMLES",
    "MAITHANALL", "MAJESAUT", "MAKEINDIA", "MALLCOM", "MALUPAPER", "MAMATA", "MANAKALUCO", "MANAKCOAT",
    "MANAKSIA", "MANAKSTEEL", "MANALIPETC", "MANAPPURAM", "MANBA", "MANCREDIT", "MANGALAM", "MANGLMCEM",
    "MANINDS", "MANINFRA", "MANKIND", "MANOMAY", "MANORAMA", "MANORG", "MANUFGBEES", "MANUGRAPH",
    "MANYAVAR", "MAPMYINDIA", "MARALOVER", "MARATHON", "MARICO", "MARINE", "MARKOLINES", "MARKSANS",
    "MARSONS", "MARUTI", "MASFIN", "MASKINVEST", "MASTEK", "MASTERTR", "MATRIMONY", "MAWANASUG",
    "MAXESTATES", "MAXHEALTH", "MAXIND", "MAYURUNIQ", "MAZDA", "MAZDOCK", "MBAPL", "MBEL",
    "MBLINFRA", "MCCHRLS-B", "MCL", "MCLEODRUSS", "MCLOUD", "MCX", "MEDANTA", "MEDIASSIST",
    "MEDICAMEQ", "MEDICO", "MEDPLUS", "MEESHO", "MEGASTAR", "MEIL", "MENNPIS", "MENONBE",
    "MEP", "MERCANTILE", "METAL", "METALIETF", "METROBRAND", "METROGLOBL", "METROPOLIS", "MFML",
    "MFSL", "MGEL", "MGL", "MHLXMIRU", "MHRIL", "MICEL", "MIDCAP", "MIDCAPADD",
    "MIDCAPBETA", "MIDCAPETF", "MIDCAPIETF", "MIDHANI", "MIDSELIETF", "MIDSMALL", "MIDWESTLTD", "MINDACORP",
    "MINDSPACE", "MINDTECK", "MIRCELECTR", "MIRZAINT", "MITCON", "MITTAL", "MKPL", "MMFL",
    "MMP", "MMTC", "MMWL", "MNC", "MOBIKWIK", "MOCAPITAL", "MODEFENCE", "MODINATUR",
    "MODIRUBBER", "MODIS", "MODISONLTD", "MODTHREAD", "MOENERGY", "MOGOLD", "MOGSEC", "MOHEALTH",
    "MOHITIND", "MOIL", "MOINFRA", "MOIPO", "MOKSH", "MOL", "MOLDTECH", "MOLDTKPAC",
    "MOLOWVOL", "MOMENTUM", "MOMGF", "MOMIDMTM", "MOMNC", "MOMOMENTUM", "MONARCH", "MONEYBOXX",
    "MONTECARLO", "MOPSE", "MOQUALITY", "MORARJEE", "MOREALTY", "MOREPENLAB", "MOSCHIP", "MOSERVICE",
    "MOSILVER", "MOTHERSON", "MOTILALOFS", "MOTISONS", "MOTOGENFIN", "MOTOUR", "MOVALUE", "MPHASIS",
    "MPSLTD", "MRF", "MRPL", "MSCIADD", "MSCIINDIA", "MSPL", "MSTCLTD", "MSUMI",
    "MTARTECH", "MTEDUCARE", "MTNL", "MUFIN", "MUFTI", "MUKANDLTD", "MUKKA", "MUKTAARTS",
    "MULTICAP", "MUNJALAU", "MUNJALSHOW", "MURUDCERA", "MUTHOOTCAP", "MUTHOOTFIN", "MUTHOOTMF", "MVGJL",
    "MWL", "NACLIND", "NAGAFERT", "NAGREEKCAP", "NAGREEKEXP", "NAHARCAP", "NAHARINDUS", "NAHARPOLY",
    "NAHARSPING", "NAM-INDIA", "NARMADA", "NATCAPSUQ", "NATCOPHARM", "NATHBIOGEN", "NATIONALUM", "NATIONSTD",
    "NAUKRI", "NAVA", "NAVINFLUOR", "NAVKARCORP", "NAVKARURB", "NAVNETEDUL", "NAZARA", "NBCC",
    "NBIFIN", "NCC", "NCLIND", "NDGL", "NDL", "NDLVENTURE", "NDRAUTO", "NDTV",
    "NEAGI", "NECCLTD", "NECLIFE", "NELCAST", "NELCO", "NEOGEN", "NEPHROPLUS", "NESCO",
    "NESTLEIND", "NETF", "NETWEB", "NEULANDLAB", "NEWGEN", "NEXTMEDIA", "NFL", "NGIL",
    "NGLFINE", "NH", "NHPC", "NIACL", "NIBE", "NIBL", "NIFTYADD", "NIFTYBEES",
    "NIFTYBETA", "NIFTYBETF", "NIFTYCASE", "NIFTYETF", "NIFTYIETF", "NIFTYQLITY", "NIITLTD", "NIITMTS",
    "NILAINFRA", "NILASPACES", "NILE", "NILKAMAL", "NIMBSPROJ", "NINSYS", "NIPPOBATRY", "NIRAJ",
    "NIRAJISPAT", "NIRLON", "NITCO", "NITINSPIN", "NITIRAJ", "NITTAGELA", "NIVABUPA", "NKIND",
    "NLCINDIA", "NMDC", "NOCIL", "NOIDATOLL", "NORBTEAEXP", "NORTHARC", "NOVAAGRI", "NOVARTIND",
    "NPBET", "NPST", "NRAIL", "NRBBEARING", "NRL", "NSIL", "NSLNISP", "NTPC",
    "NTPCGREEN", "NUCLEUS", "NURECA", "NUVAMA", "NUVOCO", "NXST", "NYKAA", "OAL",
    "OBCL", "OBEROIRLTY", "OCCLLTD", "ODIGMA", "OFSS", "OIL", "OILCOUNTUB", "OILIETF",
    "OLAELEC", "OLECTRA", "OMAXAUTO", "OMAXE", "OMFREIGHT", "OMINFRAL", "OMNI", "OMPOWER",
    "ONELIFECAP", "ONEPOINT", "ONESOURCE", "ONGC", "ONMOBILE", "ONWARDTEC", "OPTIEMUS", "ORBTEXP",
    "ORCHASP", "ORCHPHARMA", "ORICONENT", "ORIENTALTL", "ORIENTBELL", "ORIENTCEM", "ORIENTCER", "ORIENTELEC",
    "ORIENTHOT", "ORIENTLTD", "ORIENTPPR", "ORIENTTECH", "ORISSAMINE", "ORKLAINDIA", "ORTEL", "ORTINGLOBE",
    "OSIAHYPER", "OSWALAGRO", "OSWALGREEN", "OSWALPUMPS", "OSWALSEEDS", "PACEDIGITK", "PAGEIND", "PAISALO",
    "PAKKA", "PALASHSECU", "PALREDTEC", "PANACEABIO", "PANACHE", "PANAMAPET", "PANSARI", "PAR",
    "PARACABLES", "PARADEEP", "PARAGMILK", "PARAS", "PARASPETRO", "PARKHOSPS", "PARKHOTELS", "PARSVNATH",
    "PASHUPATI", "PASUPTAC", "PATANJALI", "PATELENG", "PATELRMART", "PATINTLOG", "PAUSHAKLTD", "PAVNAIND",
    "PAYTM", "PCBL", "PCJEWELLER", "PDMJEPAPER", "PDSL", "PEARLPOLY", "PENIND", "PENINLAND",
    "PERSISTENT", "PETRONET", "PFC", "PFIZER", "PFOCUS", "PFS", "PGEL", "PGHH",
    "PGHL", "PGIL", "PGINVIT", "PHARMABEES", "PHOENIXLTD", "PICCADIL", "PIDILITIND", "PIGL",
    "PIIND", "PILANIINVS", "PILITA", "PINELABS", "PIONEEREMB", "PIONRINV", "PIRAMALFIN", "PITTIENG",
    "PIXTRANS", "PKTEA", "PLASTIBLEN", "PLATIND", "PLAZACABLE", "PML", "PNB", "PNBGILTS",
    "PNBHOUSING", "PNC", "PNCINFRA", "PNGJL", "PNGSREVA", "POCL", "PODDARMENT", "POKARNA",
    "POLICYBZR", "POLYCAB", "POLYMED", "POLYPLEX", "PONNIERODE", "POONAWALLA", "POWERGRID", "POWERICA",
    "POWERINDIA", "POWERMECH", "PPAP", "PPL", "PPLPHARMA", "PRABHA", "PRADPME", "PRAENG",
    "PRAJIND", "PRAKASH", "PRAKASHSTL", "PRAVEG", "PRAXIS", "PRECAM", "PRECOT", "PRECWIRE",
    "PREMCO", "PREMEXPLN", "PREMIER", "PREMIERENE", "PREMIERPOL", "PRESTIGE", "PRICOLLTD", "PRIMESECU",
    "PRIMO", "PRINCEPIPE", "PRITI", "PRITIKAUTO", "PRIVISCL", "PROSTARM", "PROTEAN", "PROZONER",
    "PRSMJOHNSN", "PRUDENT", "PRUDMOULI", "PSB", "PSPPROJECT", "PSUBANK", "PSUBANKADD", "PSUBNKBEES",
    "PSUBNKIETF", "PTC", "PTCIL", "PTL", "PUNJABCHEM", "PURVA", "PVP", "PVRINOX",
    "PVSL", "PVTBANIETF", "PVTBANKADD", "PWL", "PYRAMID", "QGOLDHALF", "QNIFTY", "QPOWER",
    "QUADFUTURE", "QUESS", "QUICKHEAL", "QUINT", "RACE", "RACLGEAR", "RADAAN", "RADHIKAJWE",
    "RADIANTCMS", "RADICO", "RADIOCITY", "RAILTEL", "RAIN", "RAINBOW", "RAJESHEXPO", "RAJMET",
    "RAJOOENG", "RAJPALAYAM", "RAJRATAN", "RAJRILTD", "RAJSREESUG", "RAJTV", "RALLIS", "RAMANEWS",
    "RAMAPHO", "RAMASTEEL", "RAMCOCEM", "RAMCOIND", "RAMCOSYS", "RAMKY", "RAMRAT", "RANASUG",
    "RANEHOLDIN", "RATEGAIN", "RATNAMANI", "RATNAVEER", "RAYMOND", "RAYMONDLSL", "RAYMONDREL", "RBA",
    "RBLBANK", "RBZJEWEL", "RCF", "RCOM", "RECLTD", "REDINGTON", "REDTAPE", "REFEX",
    "REGAAL", "REGENCERAM", "RELAXO", "RELCHEMQ", "RELIABLE", "RELIANCE", "RELIGARE", "RELTD",
    "REMSONSIND", "RENUKA", "REPCOHOME", "REPL", "REPRO", "RESPONIND", "RETAIL", "RGL",
    "RHETAN", "RHFL", "RHIM", "RHL", "RICOAUTO", "RIIL", "RIIT", "RISHABH",
    "RITCO", "RITES", "RKDL", "RKEC", "RKFORGE", "RKSWAMY", "RMC", "RMDRIP",
    "RML", "RNBDENIMS", "ROHLTD", "ROLEXRINGS", "ROLLT", "ROML", "ROSSARI", "ROSSELLIND",
    "ROSSTECH", "ROTO", "ROUTE", "RPEL", "RPGLIFE", "RPOWER", "RPPINFRA", "RPPL",
    "RPSGVENT", "RPTECH", "RRIL", "RRKABEL", "RSDFIN", "RSL", "RSSOFTWARE", "RSWM",
    "RSYSTEMS", "RTNINDIA", "RTNPOWER", "RUBFILA", "RUBICON", "RUBYMILLS", "RUCHINFRA", "RUCHIRA",
    "RUDRA", "RUPA", "RUSHIL", "RUSTOMJEE", "RVHL", "RVNL", "RVTH", "S&SPOWER",
    "SAATVIKGL", "SADBHAV", "SADBHIN", "SADHNANIQ", "SAFARI", "SAGARDEEP", "SAGCEM", "SAGILITY",
    "SAHLIBHFI", "SAHYADRI", "SAIL", "SAILIFE", "SAIPARENT", "SAKAR", "SAKHTISUG", "SAKSOFT",
    "SAKUMA", "SALASAR", "SALONA", "SALSTEEL", "SALZERELEC", "SAMBHAAV", "SAMBHV", "SAMHI",
    "SAMMAANCAP", "SAMPANN", "SANATHAN", "SANCO", "SANDESH", "SANDHAR", "SANDUMA", "SANGAMIND",
    "SANGHVIMOV", "SANGINITA", "SANOFI", "SANOFICONR", "SANSERA", "SANSTAR", "SANWARIA", "SAPPHIRE",
    "SAPPL", "SARDAEN", "SAREGAMA", "SARLAPOLY", "SARVESHWAR", "SASKEN", "SATIA", "SATIN",
    "SAURASHCEM", "SAYAJIHOTL", "SBC", "SBCL", "SBFC", "SBGLP", "SBIBPB", "SBICARD",
    "SBIETFCON", "SBIETFIT", "SBIETFPB", "SBIETFQLTY", "SBILIFE", "SBILIQETF", "SBIMIDMOM", "SBIN",
    "SBINEQWETF", "SBISILVER", "SCANSTL", "SCHAEFFLER", "SCHAND", "SCHNEIDER", "SCI", "SCILAL",
    "SCODATUBES", "SCPL", "SDBL", "SEAMECLTD", "SECMARK", "SECURKLOUD", "SEDEMAC", "SEIL",
    "SEJALLTD", "SELECTIPO", "SELMC", "SEMAC", "SENCO", "SENORES", "SENSEXADD", "SENSEXBETA",
    "SENSEXETF", "SENSEXIETF", "SEPC", "SERVOTECH", "SESHAPAPER", "SETCO", "SETFGOLD", "SETFNIFBK",
    "SETL", "SEYAIND", "SFL", "SGFIN", "SGIL", "SGL", "SGMART", "SHADOWFAX",
    "SHAH", "SHAHALLOYS", "SHAILY", "SHAKTIPUMP", "SHALBY", "SHALPAINTS", "SHANKARA", "SHANTI",
    "SHANTIGEAR", "SHANTIGOLD", "SHARDACROP", "SHARDAMOTR", "SHARDUL", "SHAREINDIA", "SHARIABEES", "SHBAJRG",
    "SHEKHAWATI", "SHEMAROO", "SHILCTECH", "SHILPAMED", "SHINDL", "SHIVALIK", "SHIVAMAUTO", "SHIVAMILLS",
    "SHIVATEX", "SHIVAUM", "SHK", "SHOPERSTOP", "SHRADHA", "SHREDIGCEM", "SHREECEM", "SHREEJISPG",
    "SHREEPUSHK", "SHREERAMA", "SHRENIK", "SHREYANIND", "SHRIKRISH", "SHRINGARMS", "SHRIPISTON", "SHRIRAMFIN",
    "SHRIRAMPPS", "SHYAMCENT", "SHYAMMETL", "SHYAMTEL", "SICAGEN", "SICALLOG", "SIEMENS", "SIGACHI",
    "SIGIND", "SIGMA", "SIGMAADV", "SIGNATURE", "SIGNPOST", "SIKA", "SIKKO", "SIL",
    "SILGO", "SILINV", "SILLYMONKS", "SILVER", "SILVERADD", "SILVERAG", "SILVERBEES", "SILVERBETA",
    "SILVERBND", "SILVERCASE", "SILVERIETF", "SILVERTUC", "SIMPLEXINF", "SINCLAIR", "SINDHUTRAD", "SINGERIND",
    "SINTERCOM", "SIRCA", "SIS", "SITINET", "SIYSIL", "SJS", "SJVN", "SKFINDIA",
    "SKFINDUS", "SKIPPER", "SKMEGGPROD", "SKYGOLD", "SMALLADD", "SMALLCAP", "SMARTLINK", "SMARTWORKS",
    "SMCGLOBAL", "SMLMAH", "SMLT", "SMSPHARMA", "SNOWMAN", "SOBHA", "SOFTTECH", "SOLARA",
    "SOLARINDS", "SOLARWORLD", "SOLEX", "SOMANYCERA", "SOMATEX", "SOMICONVEY", "SONACOMS", "SONAL",
    "SONAMLTD", "SONATSOFTW", "SOTL", "SOUTHBANK", "SOUTHWEST", "SPAL", "SPANDANA", "SPARC",
    "SPCENET", "SPECIALITY", "SPECTRUM", "SPENCERS", "SPIC", "SPLIL", "SPLPETRO", "SPMLINFRA",
    "SPORTKING", "SRD", "SREEL", "SRF", "SRGHFL", "SRHHYPOLTD", "SRM", "SRTL",
    "SSDL", "SSFLPP", "SSWL", "STALLION", "STANLEY", "STAR", "STARCEMENT", "STARHEALTH",
    "STARPAPER", "STARTECK", "STCINDIA", "STEELCAS", "STEELCITY", "STEELXIND", "STEL", "STERTOOLS",
    "STLNETWORK", "STLTECH", "STOVEKRAFT", "STUDDS", "STYL", "STYLAMIND", "STYLEBAAZA", "STYRENIX",
    "SUBEXLTD", "SUBROS", "SUDARCOLOR", "SUDARSCHEM", "SUDEEPPHRM", "SUKHJITS", "SULA", "SUMEETINDS",
    "SUMICHEM", "SUMIT", "SUMMITSEC", "SUNCLAY", "SUNDARAM", "SUNDARMFIN", "SUNDRMBRAK", "SUNDRMFAST",
    "SUNDROP", "SUNFLAG", "SUNPHARMA", "SUNTECK", "SUNTV", "SUPERHOUSE", "SUPERSPIN", "SUPRAJIT",
    "SUPREME", "SUPREMEENG", "SUPREMEIND", "SUPREMEINF", "SUPRIYA", "SURAJEST", "SURAJLTD", "SURAKSHA",
    "SURANASOL", "SURANAT&P", "SURYALA", "SURYALAXMI", "SURYAROSNI", "SURYODAY", "SUTLEJTEX", "SUVEN",
    "SUVIDHAA", "SUYOG", "SUZLON", "SVLL", "SVPGLOB", "SWANCORP", "SWANDEF", "SWARAJENG",
    "SWELECTES", "SWIGGY", "SWSOLAR", "SYMPHONY", "SYNCOMF", "SYNGENE", "SYRMA", "SYSTMTXC",
    "TAALTECH", "TAINWALCHM", "TAJGVK", "TAKE", "TALBROAUTO", "TAMBOLIIN", "TANLA", "TARACHAND",
    "TARAPUR", "TARC", "TARIL", "TARMAT", "TARSONS", "TASTYBITE", "TATACAP", "TATACHEM",
    "TATACOMM", "TATACONSUM", "TATAELXSI", "TATAGOLD", "TATAINVEST", "TATAPOWER", "TATASTEEL", "TATATECH",
    "TATSILV", "TATVA", "TBOTEK", "TBZ", "TCC", "TCI", "TCIEXP", "TCIFINANCE",
    "TCPLPACK", "TCS", "TDPOWERSYS", "TEAMGTY", "TEAMLEASE", "TECH", "TECHM", "TECHNOE",
    "TECHNVISN", "TECILCHEM", "TEGA", "TEJASNET", "TEMBO", "TENNIND", "TERASOFT", "TEXINFRA",
    "TEXMOPIPES", "TEXRAIL", "TFCILTD", "TFL", "TGBHOTELS", "THACKER", "THAKDEV", "THANGAMAYL",
    "THEINVEST", "THEJO", "THELEELA", "THEMISMED", "THERMAX", "THOMASCOOK", "THOMASCOTT", "THYROCARE",
    "TI", "TICL", "TIGERLOGS", "TIIL", "TIINDIA", "TIJARIA", "TIL", "TILPP",
    "TIMETECHNO", "TIMEX", "TIMKEN", "TINNARUBR", "TIPSFILMS", "TIPSMUSIC", "TIRUMALCHM", "TIRUPATIFL",
    "TITAGARH", "TITAN", "TMB", "TMCV", "TMPV", "TNIDETF", "TNPETRO", "TNPL",
    "TNTELE", "TOKYOPLAST", "TOLINS", "TORNTPHARM", "TORNTPOWER", "TOTAL", "TOUCHWOOD", "TPHQ",
    "TPLPLASTEH", "TRACXN", "TRANSPEK", "TRANSRAILL", "TRANSWORLD", "TRAVELFOOD", "TREEHOUSE", "TREJHARA",
    "TREL", "TRENT", "TRF", "TRIDENT", "TRIGYN", "TRITURBINE", "TRIVENI", "TRU",
    "TRUALT", "TSFINV", "TTKHLTCARE", "TTKPRESTIG", "TTL", "TTML", "TVSELECT", "TVSHLTD",
    "TVSMNCRPS", "TVSMOTOR", "TVSSCS", "TVSSRICHAK", "TVTODAY", "TVVISION", "TWCGOLDETF", "UBL",
    "UCAL", "UCOBANK", "UDS", "UEL", "UFBL", "UFLEX", "UFO", "UGARSUGAR",
    "UGROCAP", "UJJIVANSFB", "ULTRACEMCO", "ULTRAMAR", "UMAEXPORTS", "UMESLTD", "UMIYA-MRO", "UNICHEMLAB",
    "UNIDT", "UNIECOM", "UNIENTER", "UNIINFO", "UNIMECH", "UNIONBANK", "UNIONGOLD", "UNIPARTS",
    "UNITDSPR", "UNITECH", "UNITEDPOLY", "UNITEDTEA", "UNIVASTU", "UNIVCABLES", "UNIVPHOTO", "UNOMINDA",
    "UPL", "URAVIDEF", "URBANCO", "URJA", "USHAMART", "USK", "UTIAMC", "UTKARSHBNK",
    "UTLSOLAR", "UTTAMSUGAR", "UYFINCORP", "VADILALIND", "VAIBHAVGBL", "VAISHALI", "VAKRANGEE", "VALIANTLAB",
    "VALIANTORG", "VALUE", "VARDHACRLC", "VARDMNPOLY", "VARROC", "VASCONEQ", "VASWANI", "VBL",
    "VCL", "VEDL", "VEEDOL", "VELJAN", "VENKEYS", "VENTIVE", "VENUSPIPES", "VENUSREM",
    "VERANDA", "VERTOZ", "VESUVIUS", "VETO", "VGL", "VGUARD", "VHL", "VHLTD",
    "VIDHIING", "VIDYAWIRES", "VIJAYA", "VIJIFIN", "VIKASECO", "VIKASLIFE", "VIKRAMSOLR", "VIKRAN",
    "VIMTALABS", "VINATIORGA", "VINCOFE", "VINDHYATEL", "VINEETLAB", "VINNY", "VINYLINDIA", "VIPCLOTHNG",
    "VIPIND", "VIPULLTD", "VIRINCHI", "VISACHROME", "VISAKAIND", "VISHNU", "VISHWARAJ", "VITAL",
    "VIVIDHA", "VIVIMEDLAB", "VIYASH", "VLEGOV", "VLSFINANCE", "VMART", "VMM", "VMSTMT",
    "VOLTAMP", "VOLTAS", "VPRPL", "VRAJ", "VRLLOG", "VSSL", "VSTIND", "VSTL",
    "VSTTILLERS", "VTL", "WAAREEENER", "WAAREEINDO", "WAAREERTL", "WABAG", "WAKEFIT", "WALCHANNAG",
    "WANBURY", "WCIL", "WEALTH", "WEBELSOLAR", "WEIZMANIND", "WEL", "WELCORP", "WELENT",
    "WELINV", "WELSPLSOL", "WELSPUNLIV", "WENDT", "WESTLIFE", "WEWIN", "WEWORK", "WHEELS",
    "WHIRLPOOL", "WILLAMAGOR", "WIMPLAST", "WINDLAS", "WINDMACHIN", "WINSOME", "WIPL", "WIPRO",
    "WOCKPHARMA", "WONDERLA", "WORTHPERI", "WPIL", "WSI", "WSTCSTPAPR", "XCHANGING", "XELPMOC",
    "XPROINDIA", "XTGLOBAL", "YASHO", "YATHARTH", "YATRA", "YESBANK", "YUKEN", "ZAGGLE",
    "ZEEL", "ZEELEARN", "ZEEMEDIA", "ZENITHEXPO", "ZENITHSTL", "ZENSARTECH", "ZENTEC", "ZFCVINDIA",
    "ZFSTEERING", "ZIMLAB", "ZODIAC", "ZODIACLOTH", "ZOTA", "ZSARACOM", "ZUARI", "ZUARIIND",
    "ZYDUSLIFE", "ZYDUSWELL",
}

ALL_NSE_SYMBOLS: set = {
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR",
    "SBIN", "BHARTIARTL", "KOTAKBANK", "LT", "BAJFINANCE", "HCLTECH",
    "MARUTI", "AXISBANK", "ASIANPAINT", "SUNPHARMA", "TITAN", "WIPRO",
    "ULTRACEMCO", "NTPC", "POWERGRID", "TECHM", "NESTLEIND", "ADANIENT",
    "ADANIPORTS", "DIVISLAB", "BAJAJFINSV", "COALINDIA", "INDUSINDBK",
    "ONGC", "JSWSTEEL", "TATASTEEL", "GRASIM", "HDFCLIFE", "SBILIFE",
    "CIPLA", "DRREDDY", "APOLLOHOSP", "TATACONSUM", "BPCL", "EICHERMOT",
    "HEROMOTOCO", "BRITANNIA", "SHREECEM", "DABUR", "ICICIPRULI",
    "BAJAJ-AUTO", "MARICO", "GODREJCP", "PIDILITIND", "BERGEPAINT",
    "HAVELLS", "VOLTAS", "MUTHOOTFIN", "CHOLAFIN", "TORNTPHARM",
    "LUPIN", "BIOCON", "ALKEM", "AUROPHARMA", "MANKIND", "ABBOTINDIA",
    "CANBK", "BANKBARODA", "PNB", "UNIONBANK", "FEDERALBNK", "IDFCFIRSTB",
    "BANDHANBNK", "RBLBANK", "KARURVYSYA", "SIEMENS", "ABB", "BHEL",
    "HAL", "BEL", "GRINDWELL", "CUMMINSIND", "THERMAX", "SKFINDIA",
    "DMART", "TRENT", "NYKAA", "ETERNAL", "NAUKRI", "INDIAMART",
    "IRCTC", "CONCOR", "SWIGGY", "PAYTM", "OBEROIRLTY", "DLF", "GODREJPROP", "PRESTIGE",
    "ASTRAL", "SUPREMEIND", "ATUL", "SAIL", "HINDALCO", "VEDL",
    "NMDC", "NATIONALUM", "AMBUJACEM", "ACC", "RAMCOCEM", "MOTHERSON",
    "BALKRISIND", "APOLLOTYRE", "MRF", "CEATLTD", "MFSL", "ICICIGI",
    "SBICARD", "ITC", "PAGEIND", "BATAINDIA", "TATACOMM", "POLYCAB",
    "KPITTECH", "LTTS", "PERSISTENT", "COFORGE", "MPHASIS", "TATAELXSI",
    "DIXON", "ZEEL", "SUNTV", "LALPATHLAB", "METROPOLIS", "MCX", "BSE",
    "CDSL", "RECLTD", "PFC", "HUDCO", "IRFC", "NHPC", "SJVN",
    "TORNTPOWER", "PFIZER", "GLAXO", "NAVINFLUOR", "DEEPAKNTR",
    "TATAPOWER", "ADANIGREEN", "M&M",
}

ALL_NSE_SYMBOLS: set = ALL_NSE_SYMBOLS | {
    "APLAPOLLO", "JINDALSAW", "JSWENERGY", "JPPOWER", "SUZLON", "INOXWIND",
    "CESC", "RATNAMANI", "WELCORP", "MANAPPURAM", "M&MFIN", "SCHAEFFLER",
    "TIMKEN", "KPRMILL", "ARVIND", "RAYMOND", "TRIDENT", "WELSPUNLIV",
    "VARDHMAN", "COROMANDEL", "CHAMBALFERT", "GNFC", "GSFC", "TATACHEM",
    "GHCL", "IPCALAB", "NATCOPHARM", "GLENMARK", "GRANULES", "AARTIIND",
    "VINATIORGA", "ALKYLAMINE", "SUNTECK", "KOLTEPATIL", "SOBHA", "BRIGADE",
    "HOMEFIRST", "APTUS", "AAVAS", "CREDITACC", "UJJIVANSFB", "EQUITASBNK",
    "HAPPSTMNDS", "LATENTVIEW", "ROUTE", "INTELLECT", "TANLA", "MASTEK",
    "SONATSOFTW", "CAMPUS", "METROBRAND", "MANYAVAR", "PRINCEPIPE", "HATSUN",
    "DODLA", "WESTLIFE", "DEVYANI", "JUBLFOOD", "JUBLPHARMA", "GLAND",
    "LAURUSLABS", "STRIDES", "KRBL", "BIKAJI", "ZYDUSLIFE", "CAPLIPOINT",
    "KFINTECH", "CAMS", "MEDPLUS", "KIMS", "KALYANKJIL", "THANGAMAYL",
    "ZENSARTECH", "NEWGEN", "SRF", "CENTURYPLY", "GODREJIND", "AMBER",
    "CRISIL", "EXIDEIND", "AMARAJABAT", "TVSMOTOR", "ENDURANCE",
    "HEXAWARE", "NUVAMA", "NETWORK18", "DEEPAKFERT",
}


async def get_nifty200_instrument_keys() -> dict:
    result = await get_instrument_keys_bulk(list(ALL_NSE_SYMBOLS))
    return {k: v for k, v in result.items() if v is not None}


async def get_nifty500_instrument_keys() -> dict:
    result = await get_instrument_keys_bulk(list(ALL_NSE_SYMBOLS))
    return {k: v for k, v in result.items() if v is not None}


# ---------------------------------------------------------------------------
# FastAPI router
# ---------------------------------------------------------------------------

from fastapi import APIRouter
instruments_router = APIRouter(prefix="/instruments", tags=["instruments"])


@instruments_router.post("/reload")
async def reload_endpoint() -> dict:
    try:
        count = await reload_instruments()
        return {"status": "ok", "symbols_loaded": count}
    except Exception as e:
        logger.exception("Reload failed")
        return {"status": "error", "message": str(e)}


@instruments_router.get("/search")
async def search_endpoint(q: str, limit: int = 10) -> dict:
    results = await search_instruments(q, limit)
    return {"results": results, "count": len(results)}


@instruments_router.get("/status")
async def status_endpoint() -> dict:
    await _ensure_loaded()
    return {
        "loaded": _loaded,
        "total_symbols": len(_symbol_map),
        "csv_exists": _CSV_PATH.exists(),
        "csv_path": str(_CSV_PATH),
        "sample": list(_symbol_map.keys())[:10],
    }